#!/usr/bin/env bash
# display Hol berton School 10 time

COUNTER=1
while [ $COUNTER -lt 101 ]
do
	if [ $((COUNTER%15)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((COUNTER%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((COUNTER%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "SCOUNTER"
	fi
	COUNTER=$(( COUNTER + 1))
done
