#!/usr/bin/env bash
# display informations about the holberton school file

FILE="school"

if [ -e "$FILE" ]
then
	echo "school file exist"
	if [ ! -s "$FILE" ]
	then
		echo "school filesis empty"
	else
		echo "school filesis not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular files"
	fi
else
	echo "school file does not exist"
fi
